-- Table for leaderboard notices editable from admin portal
create table if not exists public.leaderboard_notices (
  id bigint generated by default as identity primary key,
  title text,
  body text not null,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_leaderboard_notice_updated_at()
returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

create trigger trg_leaderboard_notice_updated_at
before update on public.leaderboard_notices
for each row
execute function public.set_leaderboard_notice_updated_at();
